const express = require('express')
const app = express()
const PORT = process.env.PORT || 8000

app.use(express.json())

const { checklistRouter } = require('./routes/checklist.route')
const { userRouter } = require('./routes/user.route')
const { inventoryRouter } = require('./routes/inventory.route')

const { formatted } = require('./JSONchecklists/formatted')

const { db } = require('./database/database')

console.log(JSON.stringify(formatted))
const cors=require("cors");
const corsOptions ={
   origin:'*', 
   credentials:true,            //access-control-allow-credentials:true
   optionSuccessStatus:200,
}

app.use(cors(corsOptions)) // Use this after the variable declaration

async function insertInDb() {
    await db.checklist.insert({ userId: "krillep", company: "Upper Deck", season: "1994-95", product: "Series 1", setName: "Electric Ice", personalChecklist: [] })
}

// insertInDb()

const ud9495checklist = [
    "Wayne Gretzky",	 		
    "German Titov",
    "Guy Hebert",
    "Tony Amonte",
    "Dino Ciccarelli",
    "Geoff Sanderson",
    "Alexei Zhamnov",
    "John MacLean",
    "Brent Fedyk",
    "Adam Graves",
    "Adam Oates",
    "Ron Francis",
    "Bobby Dollas",
    "Ray Ferraro",
    "Paul Broten",
    "Ulf Dahlen",
    "Pat LaFontaine",
    "Craig Janney",
    "Garry Galley",
    "Gary Roberts",
    "Bill Ranford",
    "Mario Lemieux",
    "Glen Murray",
    "Paul Coffey",
    "Corey Millen",
    "Chris Chelios",
    "Ronnie Stern",
    "Zdeno Ciger",
    "Tony Granato",	 		
    "Donald Audette",
    "Russ Courtnall",
    "Mike Gartner",
    "Marty McSorley", 		
    "Jeff Brown",
    "Mark Janssens",
    "Patrick Poulin",
    "Sergei Fedorov",
    "Tim Sweeney",
    "John Slaney",
    "Steve Larmer",
    "Dave Karpa",
    "Esa Tikkanen",
    "Joel Otto",
    "Doug Weight",
    "Murray Craven",
    "John Vanbiesbrouck",
    "Nelson Emerson",
    "Dean Evason",
    "Evgeny Davydov",
    "Craig Simpson",
    "Mats Sundin",
    "Chris Pronger",
    "Stephan Lebeau",
    "Martin Gelinas",
    "Bob Rouse",
    "Christian Ruuttu",
    "Gilbert Dionne",
    "Mike Modano",
    "Derek King",
    "Peter Stastny",
    "Ted Donato",
    "Mark Messier",
    "Dave Manson",
    "Johan Garpenlov",
    "Igor Larionov",
    "Kirk Muller",
    "Dave Ellett",
    "Dale Hunter",
    "Brent Gretzky",
    "Tom Barrasso",
    "Philippe Boucher",
    "Jesse Belanger",
    "Scott Stevens",
    "Gary Suter",
    "Tim Cheveldae",
    "Dimitri Khristich",
    "Pierre Turgeon",
    "Mike Richter",
    "Michael Nylander",
    "Sergei Krivokrasov",
    "Andy Moog",
    "Al Iafrate",
    "Bernie Nicholls",
    "Darren Turcotte",
    "Sergio Momesso",
    "Petr Klima",
    "Alexandre Daigle",
    "Joe Juneau",
    "Glen Wesley",
    "Teemu Selanne",
    "Curtis Joseph",
    "Scott Mellanby",
    "Jaromir Jagr",
    "Mark Recchi",
    "Jiri Slegr",
    "Martin Brodeur",
    "Scott Pearson",
    "Eric Lindros",
    "Larry Murphy",		
    "Sergei Zubov",		
    "Mathieu Schneider",		
    "Dale Hawerchuk",		
    "Owen Nolan",		
    "Darryl Sydor",		
    "Anatoli Semenov",		
    "Marty McInnis",		
    "Derek Mayer",		
    "Steve Duchesne",		
    "Geoff Smith",		
    "Zarley Zalapski",		
    "Rod BrindAmour",		
    "Nicklas Lidstrom",		
    "Teppo Numminen",		
    "Denny Felsner",		
    "Wendel Clark",		
    "Arturs Irbe",		
    "Josef Beranek",		
    "Brian Bradley",		
    "Eric Weinrich",		
    "Kevin Todd",		
    "Patrick Roy",		
    "Guy Carbonneau",		
    "Tom Kurvers",		
    "Sergei Makarov",		
    "Pat Peake",		
    "Danton Cole",		
    "Derian Hatcher",		
    "Kjell Samuelsson",		
    "Alexei Yashin",		
    "Chris Osgood",		
    "Kent Manderville",		
    "Jim Montgomery",		
    "Kirk McLean",		
    "Kelly Buchberger",		
    "Peter Bondra",		
    "Stephane Matteau",		
    "Oleg Petrov",		
    "Doug Gilmour",		
    "Vladimir Malakhov",		
    "Peter Zezel",		
    "Mike Vernon",		
    "Derek Plante",		
    "Valeri Zelepukin",		
    "Kevin Haller",		
    "Keith Tkachuk",		
    "Claude Boivin",		
    "Jocelyn Thibault",		
    "Jyrki Lumme",		
    "Ray Whitney",		
    "Al MacInnis",		
    "Kelly Miller",		
    "Ray Sheppard",		
    "Aaron Ward",		
    "Damian Rhodes",		
    "Jozef Stumpel",		
    "Sergei Nemchinov",		
    "Richard Matvichuk",		
    "Sean Burke",		
    "Todd Marchant",		
    "Ryan McGill",		
    "Sean Hill",		
    "Iain Fraser",		
    "Shawn McEachern",		
    "Petr Nedved",		
    "John Lilley",		
    "Joe Sacco",		
    "Jason Dawe",		
    "Mike Rathje",		
    "Phil Housley",		
    "Ron Hextall",		
    "Yves Racine",		
    "Boris Mironov",		
    "Vitali Prokhorov",		
    "Roman Hamrlik",		
    "Robert Lang",		
    "Jody Hull",		
    "Mike Ridley",		
    "Dmitri Filimonov",		
    "Rene Corbet",		
    "Rob Pearson",		
    "Richard Smehlik",		
    "Rob Gaudreau",		
    "Bill Houlder",		
    "Igor Korolev",		
    "Chris Joseph",		
    "Shane Churla",		
    "Rick Tabaracci",		
    "Alexander Godynyuk",		
    "Vladimir Konstantinov",		
    "Markus Naslund",		
    "Tom Chorske",		
    "Thomas Steen",		
    "Patrice Brisebois",		
    "Luc Robitaille",		
    "Michal Sykora",		
    "Troy Mallette",		
    "Steve Chiasson",		
    "Jimmy Carson",		
    "Mike Donnelly",
    "Mike Sillinger",
    "Martin Rucinsky",
    "Adam Bennett",
    "Matt Johnson",
    "Daren Puppa",
    "Ted Drury",
    "Jon Casey",
    "Alexei Kovalev",
    "Alexei Kasatonov",
    "Ulf Samuelsson",
    "Justin Hocking",
    "Greg Adams",
    "Greg Johnson",
    "Mike Craig",
    "Steve Konowalchuk",
    "Luke Richardson",
    "Pavol Demitra",
    "Brian Benning",
    "Corey Hirsch",
    "Alexander Semak",
    "Travis Green",
    "Turner Stevenson",
    "Dmitri Mironov",
    "Christian Soucy",
    "Rick Tocchet",
    "Craig MacTavish",
    "Wayne Gretzky",
    "Pavel Bure SE",
    "Wayne Gretzky SE",
    "Brett Hull SE",
    "Mike Gartner SE",
    "Brian Leetch SE",
    "Al MacInnis SE",
    "Dominik Hasek SE",
    "Mark Messier SE",
    "Paul Kariya SR",
    "Jamie Storr SR",
    "Jeff Friesen SR",
    "Kenny Jonsson SR",
    "Mariusz Czerkawski SR",
    "Brett Lindros SR",
    "Andrei Nikolishin SR",
    "Jason Allison SR",
    "Oleg Tverdovsky SR",
    "Brian Savage SR",
    "Peter Forsberg SR",
    "Patrik Juhlin SR",
    "Jassen Cullimore SR",
    "Chris Therien SR",
    "Kevin Brown SR",
    "Jeff Nelson SR",
    "Janne Laukkanen SR",
    "Jamie McLennan SR",
    "Craig Johnson SR",
    "Ravil Gusmanov SR",
    "Valeri Bure SR",
    "Valeri Karpov SR",
    "Mike Peca SR",
    "Brian Rolston SR",
    "Brandon Convery SR",
    "Mark Lawrence SR",
    "Adam Deadmarsh SR",
    "Jason Wiemer SR",
    "Alexander Cherbayev SR",
    "Sergei Gonchar SR",
    "Viktor Kozlov SR",
    "Vladislav Boulin SR",
    "Todd Harvey SR",
    "Cory Stillman SR",
    "David Oliver SR",
    "Andrei Nazarov SR",
    "Mikael Renberg",
    "Andrei Kovalenko",
    "Neal Broten",
    "Ed Olczyk",
    "Steve Thomas",
    "Joe Nieuwendyk",
    "Rob Gaudreau",
    "Pat Verbeek",
    "Eric Desjardins",
    "Vincent Damphousse",
    "John Cullen",
    "Garry Valk",
    "Daniel Lacroix",
    "Mike Ricci",
    "Dominik Hasek",
    "Geoff Courtnall",
    "Rob Niedermayer",
    "Alexander Karpovtsev",
    "Martin Straka",
    "Ed Belfour",
    "Dave Lowry",
    "Brendan Shanahan",
    "Jari Kurri",
    "Steven Rice",
    "Scott Levins",
    "Ray Bourque",
    "Mikael Andersson",
    "Darius Kasparaitis",
    "Chris Simon",		
    "Steve Yzerman",		
    "Don McSween",		
    "Brian Noonan",		
    "Claude Lemieux",		
    "Radek Bonk",		
    "Jason Arnott",		
    "Ian Laperriere",		
    "Pat Falloon",		
    "Kris King",		
    "Brian Bellows",		
    "Uwe Krupp",		
    "Paul Cavallini",		
    "Shaun Van Allen",		
    "Dave Andreychuk",		
    "Bobby Holik",		
    "Theoren Fleury",		
    "Mark Osborne",		
    "Andrew Cassels",		
    "Chris Tamer",		
    "Trevor Linden",		
    "Tom Fitzgerald",		
    "Ron Tugnutt",		
    "Jeremy Roenick",		
    "Todd Marchant",		
    "Scott Niedermayer",		
    "Tim Taylor",		
    "Mike Kennedy",		
    "Steve Heinze",		
    "David Sacco",		
    "Sergei Brylin",		
    "John LeClair",		
    "Brian Skrudland",		
    "Kevin Hatcher",		
    "Brett Hull",		
    "Alexander Mogilny",		
    "Sylvain Lefebvre",		
    "Sylvain Turgeon",		
    "Keith Primeau",		
    "Eric Fichaud",		
    "Jeff Beukeboom",		
    "Cory Cross",		
    "Daigneault",		
    "Stephen Leach",		
    "Zigmund Palffy",		
    "Igor Korolev",		
    "Chris Gratton",		
    "Joe Mullen",		
    "Brent Gilchrist",		
    "Adam Creighton",		
    "Dimitri Yushkevich",		
    "Wes Walz",		
    "Shayne Corson",		
    "Eric Lacroix",		
    "Maxim Bets",		
    "Sylvain Cote",		
    "Valeri Kamensky",		
    "Shjon Podein",		
    "Robert Reichel",		
    "Cliff Ronning",		
    "Bill Gin",		
    "Dallas Drake",		
    "Robert Petrovicky",		
    "Ken Wregget",		
    "Todd Elik",		
    "Cam Neely",		
    "Darren McCarty",		
    "Shean Donovan",		
    "Felix Potvin",		
    "Yuri Khmylev",		
    "Mark Tinordi",		
    "Craig Billington",		
    "Patrick Flatley",		
    "Jocelyn Lemieux",		
    "Vyacheslav Kozlov",		
    "Trent Klatt",		
    "Geoff Sarjeant",		
    "Bob Kudelski",		
    "Stanislav Neckar",		
    "Jon Rohloff",		
    "Jeff Shantz",		
    "Dale Craigwell",		
    "Adrien Plavsic",		
    "Dave Gagner",		
    "Dave Archibald",		
    "Gilbert Dionne",		
    "Troy Loney",		
    "Dean McAmmond",		
    "Pauli Jaks",		
    "Stephane Richer",		
    "Don Beaupre",		
    "Kevin Stevens",		
    "Brad May",		
    "Neil Wilkinson",		
    "Kevin Lowe",		
    "Fredrik Olausson",		
    "Trevor Kidd",		
    "Brent Grieve",		
    "Dominic Roussel",		
    "Bret Hedican",		
    "Bryan Smolinski",
    "Doug Lidster",
    "Bob Errey",
    "Pierre Sevigny",
    "Rob Brown",
    "Joe Sakic",
    "Nikolai Borschevsky",
    "Martin Lapointe",
    "Jean-Yves Roy",
    "Robert Kron",
    "Tie Domi",
    "Jim Dowd",
    "Keith Jones",
    "Scott Lachance",
    "Bob Corkum",
    "Denis Chasse",
    "Denis Savard",
    "Joe Murphy",
    "Vyacheslav Butsayev",
    "Mattias Norstrom",
    "Sergei Zholtok",
    "Nikolai Khabibulin",
    "Pat Elynuik",
    "Doug Brown",
    "Dave McLlwain",
    "James Patrick",
    "Alexander Selivanov",
    "Scott Thornton",
    "Todd Ewen",
    "Peter Popovic",
    "Jarkko Varvio",
    "Paul Ranheim",
    "Kevin Dineen",
    "Kelly Hrudey",
    "Michal Grosek",
    "Viacheslav Fetisov",
    "Ivan Droppa",
    "Benoit Hogue",
    "Sheldon Kennedy",
    "Gord Murphy",
    "Jamie Baker",
    "Todd Gill",
    "Mark Recchi",
    "Ted Crowley",
    "Ryan Smyth",
    "Brian Leetch",
    "Bob Sweeney",
    "Don Sweeney",
    "Byron Dafoe",
    "Nathan Lafayette",
    "Keith Carney",
    "Stephane Fiset",
    "Kevin Miller",
    "Craig Darby",
    "Vlastimil Kroupa",
    "Rob Zettler",
    "Glenn Healy",
    "Todd Simon",
    "Mark Fitzpatrick",
    "Drake Berehowsky",
    "Darcy Wakaluk",
    "Enrico Ciccone",
    "Tomas Sandstrom",
    "Mikhail Shtalenkov",
    "Igor Kravchuk",
    "Jamie Allison",
    "Gino Odjick",
    "Norm Maciver",
    "Terry Carkner",
    "Rob Zamuner",
    "Pavel Bure",
    "Patrice Tardif",
    "Andrei Lomakin",
    "Kirk Maltby",
    "Jaroslav Modry",
    "Tommy Soderstrom",
    "Patrik Carnback",
    "Jeff Reese",
    "Todd Krygier",
    "John McIntyre",
    "Joey Kocur",
    "Steve Rucchin",
    "Bob Bassen",
    "Marek Malik",
    "Darryl Shannon",
    "Shawn Burr",
    "Louie DeBrusk",
    "Olaf Kolzig",
    "Cam Stewart",
    "Rob Blake",
    "Eric Charron",
    "Sandis Ozolinsh",
    "Paul Ysebaert",
    "Kris Draper",
    "Stu Barnes",
    "Doug Bodger",
    "Blaine Lacher",
    "Ed Jovanovski WJC",
    "Eric Daze WJC",
    "Dan Cloutier WJC",
    "Chad Allan WJC",			
    "Todd Harvey WJC",			
    "Jamie Rivers WJC",			
    "Bryan McCabe WJC",			
    "Darcy Tucker WJC",			
    "Wade Redden WJC",			
    "Nolan Baumgartner WJC",			
    "Marek Malik WJC",			
    "Petr Cajanek WJC",			
    "Jan Hlavac WJC",			
    "Ladislav Kohn WJC",			
    "Kimmo Timonen WJC",			
    "Antti Aalto WJC",			
    "Tommi Rajamaki WJC",			
    "Vitali Yachmenev WJC",			
    "Vadim Epantchinsev WJC",			
    "Dmitri Klevakin WJC",			
    "Nikolai Zavaroukhine WJC",			
    "Alexandre Koroliouk WJC",			
    "Anders Eriksson WJC",			
    "Jesper Mattsson WJC",			
    "Mattias Ohlund WJC",			
    "Anders Soderberg WJC",			
    "Bryan Berard WJC",			
    "Jason Bonsignore WJC",			
    "Deron Quint WJC",			
    "Richard Park WJC",			
    "Jeff Friesen CC",			
    "Paul Kariya CC",			
    "Peter Forsberg CC",			
    "Zigmund Palffy CC",			
    "Kenny Jonsson CC",			
    "Jamie Storr CC",			
    "Alexander Selivanov CC",			
    "Mike Peca CC",			
    "Mariusz Czerkawski CC",			
    "Jason Allison CC",			
    "Todd Harvey CC",			
    "Brett Lindros CC",			
    "Radek Bonk CC",			
    "Blaine Lacher CC",			
    "Oleg Tverdovsky CC",			
    "Wayne Gretzky WT",			
    "Radek Bonk WT",			
    "Mariusz Czerkawski WT",			
    "Jaromir Jagr WT",			
    "Dominik Hasek WT",			
    "Todd Harvey WT",			
    "Mike Peca WT",			
    "Mats Sundin WT",			
    "Doug Weight WT",			
    "Steve Yzerman WT",			
    "Brett Lindros WT",			
    "Alexander Mogilny WT",			
    "Patrik Juhlin WT",			
    "Alexei Yashin WT",			
    "Peter Forsberg WT",			
    "Michael Nylander WT",			
    "Teemu Selanne WT",			
    "Marek Malik WT",			
    "Jari Kurri WT",			
    "Kenny Jonsson WT",			
    "Mikael Renberg WT",			
    "Adam Deadmarsh WT",			
    "Mark Messier WT",			
    "Rob Blake WT",			
    "Janne Laukkanen WT",			
    "Theoren Fleury WT",			
    "Alexei Kovalev WT",			
    "Jamie Storr WT",			
    "Brett Hull WT",			
    "Valeri Karpov WT"
]

function stringify(checklist) {
    return JSON.stringify(checklist)
}

const jsonV = stringify(ud9495checklist)
// console.log(jsonV)


app.use('/api/checklist', checklistRouter)
app.use('/api/inventory', inventoryRouter)
app.use('/api/user', userRouter)





app.listen(PORT, () => {
    console.log("Started server at port " + PORT)
})

